name: Deploy

on:
  push:
    branches:
      - main


jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-node@v1.0.0
        with:
          node-version: 18
      - uses: actions/setup-elixir@v1.0.0
        with:
          elixir-version: 1.18.0
          otp-version: 26.0
      - run: mix deps.get
      - run: mix compile
      - run: mix release
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t food-order-producao .
      - run: docker tag food-order-producao:latest diegogl12/food-order-producao:latest
      - run: docker push diegogl12/food-order-producao:latest
